---

- hosts: k3s_cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/prereq, tags: ["k3s","prereq"] }
    - { role: k3s/download, tags: ["k3s","prereq"] }
    - { role: raspberrypi, tags: ["raspi"] }


- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master, tags: ["k3s"] }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node, tags: ["k3s"] }

## deploy k8s apps
- hosts: master
  gather_facts: yes
  roles:
    - { role: k8s/pihole, tags: ["k8s","pihole"] }
#    - { role: k8s/rundeck, tags: ["k8s","rundeck"] }
#    - { role: k8s/gitlab, tags: ["k8s","gitlab"] }
