---

- hosts: k3s-cluster
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/prereq }
    - { role: k3s/download }
    - { role: raspberrypi }


- hosts: master
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/master }

- hosts: node
  gather_facts: yes
  become: yes
  roles:
    - { role: k3s/node }
