---
- name: Activating cgroup support
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: reboot

- name: Flush iptables before changing to iptables-legacy
  iptables:
    flush: true
  changed_when: false   # iptables flush always returns changed

- name: Changing to iptables-legacy
  alternatives:
    path: /usr/sbin/iptables-legacy
    name: iptables
  register: ip4_legacy

- name: Changing to ip6tables-legacy
  alternatives:
    path: /usr/sbin/ip6tables-legacy
    name: ip6tables
  register: ip6_legacy

- name: Install general apt packages
  apt:
    name: "{{ apt_pkgs }}"
    state: present

- name: Install pip packages
  pip:
    name: "{{ pip_pkgs }}"

- name: Download and install helm
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-arm.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: "--strip-components=1"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Instal fail2ban package
  apt:
    name: fail2ban

- name: Configure fail2ban local jail
  template:
    src: fail2ban.j2
    dest: /etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Install unattended-upgrades to perform security updates automatically
  apt:
    name: unattended-upgrades
    state: present

- name: Add docker signing key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker repository into sources list
  apt_repository:
    repo: "deb [arch=armhf] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker apt package
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes

- name: Add pi user to the docker user group
  user:
    name: pi
    group: docker