---

- name: Add bitnami (postgresql) chart repo
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Deploy rundeck postgresql db helm chart
  community.kubernetes.helm:
    name: rundeck-db
    chart_ref: bitnami/postgresql
    release_namespace: rundeck
    values: "{{ lookup('template', 'rundeck-db-values.yml.j2') | from_yaml }}"
