---
- name: Disable master service
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - k3s
  when: groups['master'] is defined and inventory_hostname in groups['master']

- name: Disable worker services
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - k3s-agent
  when: groups['node'] is defined and inventory_hostname in groups['node']

- name: Remove service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ systemd_dir }}/k3s.service"
    - "{{ systemd_dir }}/k3s-agent.service"
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s
    - /var/lib/kubelet
    - /usr/local/bin/k3s

- name: daemon_reload
  systemd:
    daemon_reload: yes
